timeVAE:
  latent_dim: 24
  hidden_layer_sizes:
#    - 150
#    - 300
#    - 500
  - 30
  - 30
  - 50
  reconstruction_wt: 10
  batch_size: 64
  use_residual_conn: true
  trend_poly: 0
  custom_seas: null

vae_dense:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 64

vae_conv:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 1
  batch_size: 64
